### ISSUE TITLE
Empty tables, even when returned from queries on empty datasets, should always have their columns

### ISSUE THREAD

**Issue by clayote** [lllangWV/ParquetDB#5]
I'm writing a bunch of "update or create" functions. The update part gets the ids to be updated first, if they exist.

I'm using a pattern not unlike this one, for cases where Arrow filters alone aren't expressive enough

```python
def iter_table():
    for d in ParquetDB("table").read(filters=filters, columns=["id"])["id"]:
        if condition(d):
            yield d
```

But it doesn't really work, because if the table happens not to have been created yet (rather than merely not having any rows in it) then ParquetDB gives me a `KeyError`.

I think the empty table returned by queries with no matches should still have all the columns that a match does.

**Comment by lllangWV** [comment]
Hey Clayote,

I attempted to reproduce the error you're encountering and I think I’ve figured it out. If no tables exist in the dataset yet, calling read results in an error saying the `id` field doesn’t exist. Since id is a special column name, I believe it should always be present, even when no tables have been created. How I currently have it, it just produces `KeyError: 'Field "id" does not exist in schema'.

Does that sound accurate to you?

**Comment by lllangWV** [comment]
I made a change where it will always return the id column:

```python 
db = ParquetDB(dataset_name='dev')

table=db.read(columns=['id'])

print(f"Table shape: {table.shape}")
print(f"Table: {table}\n")
print(f"Empty Chunked Array: {type(table['id'])}" )
print(f"Empty Chunked Array: {table['id']}")
```


Output:
```bash
Table shape: (0, 1)
Table: pyarrow.Table
id: int64
----
id: [[]]

Empty Chunked Array: <class 'pyarrow.lib.ChunkedArray'>
Empty Chunked Array: [
  []
]
```

Is this what you wanted?

Logan Lang

**Comment by clayote** [comment]
Yeah, that's correct.

Cheers!
